name: isp_management
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.17.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^1.3.0
  package_info_plus: ^3.1.2
  path: ^1.8.2
  path_provider: ^2.0.14
  riverpod_annotation: ^2.1.1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.2.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
